bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'
urlpatterns = [
    path('', views.bbs, name='bbs'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.CategoryList.as_view(), name='category'),
    path('<str:slug>/', views.postList, name='postList'),
    path('<str:slug>/<int:pk>/', views.PostDetail.as_view(), name='postDetail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('blog/', include('blog.urls')),
    path('bbs/', include('bbs.urls')),
    path('', include('page.urls')),
]

handler404 = 'page.views.page_not_found'
handler404 = 'page.views.server_error'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.diary, name='main'),
    path('upload_image/', views.uploadImage, name='upload_image'),
    path('delete_image/<int:image_id>/', views.deleteImage, name='delete_image'),
    path('create_reply/<int:image_id>/', views.createReply, name='create_reply'),
    path('delete_reply/<int:reply_id>/', views.deleteReply, name='delete_reply')
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'
urlpatterns = [
    path('', views.index, name='main'),
]

bbs/models.py
from django.db import models

class Guest(models.Model):
    name = models.CharField('NAME', max_length=20)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '%s %s' % (self.date, self.name)

class Reply(models.Model):
    guestid = models.ForeignKey(Guest, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=40)
    content = models.TextField(blank=True)
    def __str__(self):
        return self.name

blog/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    thumnail = models.ImageField(upload_to='blog')
    slug_url = models.SlugField(
        max_length=200, unique=True, allow_unicode=True)
    order = models.IntegerField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:postList', args=[self.slug])


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    thumbnail = models.ImageField(
        upload_to='blog/%Y/%m/%d', blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    category = models.ForeignKey(
        Category, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:postDetail', args=[self.category.slug_url, self.id])


class Image(models.Model):
    image = models.ImageField(upload_to='blog/%Y/%m/%d')
    post = models.ForeignKey(Post, null=True, on_delete=models.SET_NULL)

diary/models.py
from django.db import models


class Image(models.Model):
    image = models.ImageField(upload_to='diary/%Y/%m/%d')
    date = models.DateTimeField(auto_now_add=True)
    password = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d %H:%M:%S")


class Reply(models.Model):
    imageid = models.ForeignKey(Image, on_delete=models.CASCADE)
    name = models.CharField(max_length=40, blank=True)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    password = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.name

page/models.py
from django.db import models

# Create your models here.

bbs/forms.py
from django import forms
from .models import Guest

class GuestForm(forms.ModelForm):
    class Meta:
        model = Guest
        fields = ['name', 'content']
        labels = {
            'name': '닉네임',
            'content': '내용',
        }

diary/forms.py
from django import forms
from .models import Image, Reply

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'password']
        widgets = {
            'image' : forms.FileInput(attrs={'id' : 'input_image_file'}),
            'password' : forms.PasswordInput(attrs={'id' : 'input_image_password'}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['name', 'content', 'password']
        labels = {
            'name': '닉네임',
            'content': '내용',
            'password': '비밀번호',
        }

bbs/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Guest, Reply
from .forms import GuestForm

def bbs(request):
    page = request.GET.get('page', '1')
    reply_list = Reply.objects.order_by('-id')
    paginator = Paginator(reply_list, 5)
    page_obj = paginator.get_page(page)
    form = GuestForm()
    if request.method == 'POST':
        form = GuestForm(request.POST)
        if form.is_valid():
            guest = form.save()
            return redirect('bbs:bbs')
    return render(
        request,
        'bbs/reply_list.html',
        {
            'reply_list': page_obj,
            'form': form
        })

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Category, Post, Image


class CategoryList(ListView):
    model = Category
    template_name = 'blog/Category_list.html'


def postList(request, slug):
    category = Category.objects.get(slug_url=slug)
    post_list = Post.objects.filter(category=category).order_by('-create_date')

    return render(
        request,
        'blog/Post_list.html',
        {
            'post_list': post_list,
            'category': category,
        }
    )


class PostDetail(DetailView):
    model = Post
    template_name = 'blog/Post_detail.html'

diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.hashers import make_password, check_password
from .models import Image, Reply
from .forms import ImageForm, ReplyForm
import hashlib

def diary(request):
    page = request.GET.get('page', '1')
    image_list = Image.objects.order_by('-id')
    paginator = Paginator(image_list, 5)
    page_obj = paginator.get_page(page)
    image_form = ImageForm
    return render(
        request,
        'diary/diary_list.html',
        {
            'image_list' : page_obj,
            'reply_set' : Reply,
            'image_form' : image_form,
        })


def uploadImage(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.password = make_password(image.password)
            image.save()
    return redirect('diary:main')


def deleteImage(request, image_id):
    if request.method == 'POST':
        image = get_object_or_404(Image, pk=image_id)
        if request.POST['password'] != '':
            if check_password(request.POST['password'], image.password):
                image.delete()
    return redirect('diary:main')


def createReply(request, image_id):
    if request.method == 'POST':
        image = get_object_or_404(Image, pk=image_id)
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.imageid = image
            reply.password = make_password(reply.password)
            reply.save()
    return redirect('diary:main')


def deleteReply(request, reply_id):
    if request.method == 'POST':
        reply = get_object_or_404(Reply, pk=reply_id)
        if request.POST['password'] != '':
            if check_password(request.POST['password'], reply.password):
                reply.delete()
    return redirect('diary:main')

page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main.html')

def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, '404.html')

def server_error(request, exception):
    """
    500 Page not found
    """
    return render(request, '404.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <title>{% block title %}{% endblock%}Aeternus</title>
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/styles/default.min.css">
</head>
<body>
  <div id="allpage">
    <div id="menu">
      <img src="{% static 'menu.png' %}" width="400" height="400" alt="메뉴이미지" usemap="#menuMap">
      <map name="menuMap" id="menuMap">
        <area shape="poly" coords="199,0,137,93,199,187,262,93"     alt="Main"      title="Main"      target="_self"  href="/">
        <area shape="poly" coords="131,106,68,199,131,293,194,199"  alt="Diary"     title="Diary"     target="_self"  href="/diary/">
        <area shape="poly" coords="268,106,205,199,268,293,331,199" alt="Favorite"  title="Favorite"  target="_self"  href="/blog/">
        <area shape="poly" coords="199,212,137,305,199,399,262,305" alt="GuestBook" title="GuestBook" target="_self"  href="/bbs/">
      </map>
      <h1>Aeternus</h1>
    </div>
    <div id="sub_menu">
      <h1>Aeternus</h1>
      <a href="{% url 'page:main' %}"><img src="{% static 'menu1.png' %}" width="100%" alt="Main"></a>
      <a href="{% url 'diary:main' %}"><img src="{% static 'menu2.png' %}" width="100%" alt="Diary"></a>
      <a href="{% url 'blog:category' %}"><img src="{% static 'menu3.png' %}" width="100%" alt="Favorite"></a>
      <a href="{% url 'bbs:bbs' %}"><img src="{% static 'menu4.png' %}" width="100%" alt="Guest"></a>
    </div>
    <div id="content">
      <!-- 기본 템플릿 안에 삽입될 내용 Start -->
      {% block content %}
      {% endblock %}
      <!-- 기본 템플릿 안에 삽입될 내용 End -->
      <hr class='endhr'>
      <p><a href="javascript:window.scrollTo(0,0);">↑Top</a><span class="right">made by 사월</span></p>
    </div>
  </div>
  <script src="{% static 'script.js' %}"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
</body>

</html>

templates/bbs/reply_list.html
{% extends 'base.html' %}
{% block content %}
<h2>Guest Book</h2>
<form method="post" name="reply">
  {% csrf_token %}
  {% if form.errors %}{% for field in form %}{% if field.errors %}
    <p><strong>{{ field.label }}을 입력해주세요.</strong></p>
  {% endif %}{% endfor %}{% endif %}
  <div id="input_guest">
    <div id="input_guest_content">
      <textarea name="content" placeholder="남기실 메세지가 있다면 적어주세요!">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <div id="input_guest_name">
      <input type="text" name="name" placeholder="닉네임" value="{{ form.name.value|default_if_none:'' }}">
      <input type="submit" value="전송">
    </div>
  </div>
</form>
<h1>Thanks For</h1>
{% if reply_list %}
  <div class="reply_list">
    {% for reply in reply_list %}
      <h3>{{ reply.name }}<span>▽</span></h3>
      <p class="hidden">{{ reply.content }}</p>
    {% endfor %}
  </div>
{% endif %}

  <div class="page_control">
  <!-- 이전페이지 -->
  {% if reply_list.has_previous %}
    <a class="page-link" href="?page={{ reply_list.previous_page_number }}">&lt;이전페이지 /</a>
  {% endif %}
  <!-- 다음페이지 -->
  {% if reply_list.has_next %}
    <a class="page-link" href="?page={{ reply_list.next_page_number }}">/ 다음페이지&gt;</a>
  {% endif %}
  </div>

{% endblock %}

templates/blog/Category_list.html
{% extends 'base.html' %}
{% block content %}
<h2>Favorite</h2>

<div id="category_list">
  {% for category in object_list %}
    <a href="{% url 'blog:postList' category.slug_url %}">
      <div class='category_card'>
        <div class='category_thumbnail'><img src="{{ category.thumnail.url }}"></div>
      <p>{{ category.name }}</p>
      </div>
    </a>
  {% endfor %}
</div>

{% endblock %}

templates/blog/Post_detail.html
{% extends 'base.html' %}
{% load markdown_filter %}

{% block title %}{{ object.title }} - {% endblock %}

{% block content %}
<h2><span class='more_letter'>[{{ object.category }}]</span> {{ object.title }}</h2>
<p class='date'>{{ object.create_date }} 생성
{% if object.update_date != object.create_date %}<br> {{ object.update_date }} 수정{% endif %}</p>

<div id="post">
  {{ object.content|mark }}
</div>

{% endblock %}

templates/blog/Post_list.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ category }}</h2>

<ul id="post_list">
  {% for post in post_list %}
  <a href="{% url 'blog:postDetail' post.category.slug_url post.id %}">
    <li class='post_title'>
      {% if post.thumbnail %}
      <div class="postThumbnail"><img src="{{ post.thumbnail.url }}"></div>
      {% endif %}
      {{ post.title }}
    </li>
  </a>
  {% endfor %}
</ul>

{% endblock %}

templates/diary/diary_list.html
{% extends 'base.html' %}
{% load markdown_filter %}
{% load static %}
{% block content %}
<h2>Diary</h2>

<form method="post" action="{% url 'diary:upload_image' %}" enctype="multipart/form-data" name="image">
  {% csrf_token %}
  <div id="input_image">
    <label>
      <img src="{% static 'diary/icon-image.png' %}" alt="upload image button" />
      업로드 이미지
      <input class="hidden" type="file" accept="image/*" name="image">
    </label>
    <input type="password" name="password" placeholder="비밀번호">
    <input type="submit" value="업로드">
  </div>
</form>

<div id="diary">
  {% for image in image_list %}
  <div class="page">
    <span class="page_id">no.{{ image.id }}</span>

    <div class="image_delete right">
      <span>삭제</span>
      <form class="hidden" method="post" action="{% url 'diary:delete_image' image.id %}" name="delete_image_{{ image.id }}">
        {% csrf_token %}
        <input type="password" name="password" placeholder="삭제 비밀번호">
        <input type="submit" value="삭제">
      </form>
    </div>

    <div class="image">
      <img src="{{ image.image.url }}">
    </div>

    {% for reply in image.reply_set.all %}
    <div class="reply">
      <p>{{ reply.name }} - {{ reply.date }}</p>
      <p>{{ reply.content|mark }}</p>
      <div class="reply_delete">
        <span>삭제</span>
        <form class="hidden" method="post" action="{% url 'diary:delete_reply' reply.id %}" name="delete_reply_{{ reply.id }}">
          {% csrf_token %}
          <input type="password" name="password" placeholder="삭제 비밀번호">
          <input type="submit" value="삭제">
        </form>
      </div>
    </div>
    {% endfor %}
    <div class="reply_button">리플 추가</div>
    <div class="input_reply hidden">
      <form method="post" action="{% url 'diary:create_reply' image.id %}" name="reply_{{ image.id }}">
        {% csrf_token %}
        <textarea name="content" placeholder="댓글을 남겨주세요"></textarea>
        <input type="text" name="name" placeholder="닉네임">
        <div class="right">
          <input type="password" name="password" placeholder="비밀번호">
          <input type="submit" value="등록">
        </div>
      </form>
    </div>
  </div>
  {% endfor %}
</div>

<div class="page_control">
  <!-- 이전페이지 -->
  {% if image_list.has_previous %}
  <a class="page-link" href="?page={{ image_list.previous_page_number }}">&lt;이전페이지 /</a>
  {% endif %}
  <!-- 다음페이지 -->
  {% if image_list.has_next %}
  <a class="page-link" href="?page={{ image_list.next_page_number }}">/ 다음페이지&gt;</a>
  {% endif %}
</div>

{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>사월:April</h2>
<p>
  e-mail : april35592@gmail.com<br>
  <a href="https://github.com/april35592" target="_blank">github</a>
  /
  <a href="https://www.notion.so/april0ys/2021-6a17af7dfa904501afa2bd76d099af6b" target="_blank">notion</a>
  /
  <a href="https://twitter.com/niv_nip" target="_blank">twitter</a>
</p>
<br>
<img src="{% static 'banner.png' %}" width="200" height="40" alt="배너"/>
<p>
  site: http://april0ys.pe.kr/<br>
  banner: http://april0ys.pe.kr/static/banner.png
</p>
{% endblock %}